from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QFileDialog

class Ui_mainApplication(object):
    def setupUi(self, mainApplication):
        mainApplication.setObjectName("mainApplication")
        mainApplication.resize(505, 595)
        self.centralwidget = QtWidgets.QWidget(mainApplication)
        self.centralwidget.setObjectName("centralwidget")
        self.addWordButton = QtWidgets.QPushButton(self.centralwidget)
        self.addWordButton.setGeometry(QtCore.QRect(230, 490, 191, 51))
        self.addWordButton.setObjectName("addWordButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(310, 330, 101, 51))
        self.nextButton.setObjectName("nextButton")
        self.flipButton = QtWidgets.QPushButton(self.centralwidget)
        self.flipButton.setGeometry(QtCore.QRect(200, 330, 91, 51))
        self.flipButton.setObjectName("flipButton")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(80, 330, 101, 51))
        self.prevButton.setObjectName("prevButton")
        self.definitionInputField = QtWidgets.QTextEdit(self.centralwidget)
        self.definitionInputField.setGeometry(QtCore.QRect(70, 420, 351, 61))
        self.definitionInputField.setObjectName("definitionInputField")
        self.wordNameInputField = QtWidgets.QLineEdit(self.centralwidget)
        self.wordNameInputField.setGeometry(QtCore.QRect(70, 390, 351, 20))
        self.wordNameInputField.setObjectName("wordNameInputField")
        self.removeWordButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeWordButton.setGeometry(QtCore.QRect(80, 490, 141, 51))
        self.removeWordButton.setObjectName("removeWordButton")
        self.displayField = QtWidgets.QTextEdit(self.centralwidget)
        self.displayField.setGeometry(QtCore.QRect(20, 20, 391, 301))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.displayField.setFont(font)
        self.displayField.setAutoFillBackground(True)
        self.displayField.setReadOnly(True)
        self.displayField.setObjectName("displayField")
        self.setListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.setListWidget.setGeometry(QtCore.QRect(420, 30, 71, 192))
        self.setListWidget.setObjectName("setListWidget")
        self.loadSelectedButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadSelectedButton.setGeometry(QtCore.QRect(420, 230, 75, 23))
        self.loadSelectedButton.setObjectName("loadSelectedButton")
        self.setFilDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.setFilDirButton.setGeometry(QtCore.QRect(420, 290, 75, 23))
        self.setFilDirButton.setObjectName("setFilDirButton")
        self.saveSelectedButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveSelectedButton.setGeometry(QtCore.QRect(420, 260, 75, 23))
        self.saveSelectedButton.setObjectName("saveSelectedButton")
        mainApplication.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainApplication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainApplication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainApplication)
        self.statusbar.setObjectName("statusbar")
        mainApplication.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(mainApplication)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(mainApplication)
        self.actionLoad.setObjectName("actionLoad")
        self.actionFileList = QtWidgets.QAction(mainApplication)
        self.actionFileList.setObjectName("actionFileList")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainApplication)
        QtCore.QMetaObject.connectSlotsByName(mainApplication)

    def retranslateUi(self, mainApplication):
        _translate = QtCore.QCoreApplication.translate
        mainApplication.setWindowTitle(_translate("mainApplication", "MainWindow"))
        self.addWordButton.setText(_translate("mainApplication", "ADD WORD"))
        self.nextButton.setText(_translate("mainApplication", "NEXT"))
        self.flipButton.setText(_translate("mainApplication", "FLIP"))
        self.prevButton.setText(_translate("mainApplication", "PREV"))
        self.removeWordButton.setText(_translate("mainApplication", "REMOVE WORD"))
        self.displayField.setHtml(_translate("mainApplication", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Semibold\'; font-size:40pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.loadSelectedButton.setText(_translate("mainApplication", "Load"))
        self.setFilDirButton.setText(_translate("mainApplication", "Set File Dir"))
        self.saveSelectedButton.setText(_translate("mainApplication", "Save"))
        self.menuFile.setTitle(_translate("mainApplication", "File"))
        self.actionSave.setText(_translate("mainApplication", "Save"))
        self.actionLoad.setText(_translate("mainApplication", "Load"))
        self.actionFileList.setText(_translate("mainApplication", "FileList"))
